# Generated by Django 4.0.4 on 2022-04-23 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='lastname_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='unit_price',
        ),
    ]
