# Generated by Django 4.0.4 on 2022-04-23 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_lastname_name_customer_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='burth_date',
            new_name='birth_date',
        ),
    ]
