# Generated by Django 4.0.4 on 2022-04-23 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_burth_date_customer_birth_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='palaced_at',
            new_name='placed_at',
        ),
    ]
